default: &default
  adapter: sqlite3
  username: your_username
  password: your_password
  host: 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/todolist_development.sqlite3

test:
  <<: *default
  database: db/todolist_test.sqlite3
  
production:
  <<: *default
  database: todolist_production
